#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Sep 11 15:47:58 2020

@author: bcbirkel
"""

from obspy import read, read_inventory
from obspy.signal.filter import bandpass
import pandas as pd
from mpl_toolkits.basemap import Basemap
import matplotlib.pyplot as plt
import numpy as np
from obspy.signal.invsim import simulate_seismometer, corn_freq_2_paz
from obspy.geodetics import gps2dist_azimuth
from obspy.io.sac import sacpz
from obspy.io.sac import attach_paz
from obspy.io.gse2.paz import read_paz
import os
from obspy.core import Trace, Stream, AttribDict
from obspy.signal.rotate import rotate_ne_rt
import math
import obspy.realtime.signal as signal
from obspy.core.utcdatetime import UTCDateTime
import shutil

#Ignore warnings due to python 2 and 3 conflict
import warnings
warnings.filterwarnings("ignore")


# %% Set parameters
#set event
for i in range(1):
    event_no = 0
    events = ['lahabra_2014', 'beverlyhills_2001', 'chatsworth_2007', 'chinohills_2008', 'inglewood_2009']
    event = events[event_no]
    
    # %% Set paths
    
    path_dir_CESMD = './CompiledEvents/' + event + '/allData/'

    if event_no == 0:
        event_title = 'lahabra'
        event_lat = 33.9325
        event_lon = -117.9158
        start = UTCDateTime("2014-03-29T04:09:42.994500Z") 
        stream_cesmdN = read(path_dir_CESMD + "*N_vel.SAC") 
        stream_cesmdE = read(path_dir_CESMD + "*E_vel.SAC")
        stream_cesmdZ = read(path_dir_CESMD + "*Z_vel.SAC")
    elif event_no == 3:
        event_title = 'chinohills'
        event_lat = 33.9465
        event_lon = -117.7667
        stream_cesmdN = read(path_dir_CESMD + "*N_vel.SAC") + read(path_dir_CESMD + "*N.*.SAC")
        stream_cesmdE = read(path_dir_CESMD + "*E_vel.SAC")+ read(path_dir_CESMD + "*E.*.SAC")
        stream_cesmdZ = read(path_dir_CESMD + "*Z_vel.SAC")+ read(path_dir_CESMD + "*Z.*.SAC")

    elif event_no == 4:
        event_title = 'inglewood'
        event_lat = 33.9377
        event_lon = -118.3357
        stream_cesmdN = read(path_dir_CESMD + "*N_vel.SAC")
        stream_cesmdE = read(path_dir_CESMD + "*E_vel.SAC")
        stream_cesmdZ = read(path_dir_CESMD + "*Z_vel.SAC")
    elif event_no == 2:
        event_title = 'chatsworth'
        event_lat = 34.2983
        event_lon = -118.6255
        stream_cesmdN = read(path_dir_CESMD + "*N_vel.SAC") + read(path_dir_CESMD + "*N.*.SAC")
        stream_cesmdE = read(path_dir_CESMD + "*E_vel.SAC")+ read(path_dir_CESMD + "*E.*.SAC")
        stream_cesmdZ = read(path_dir_CESMD + "*Z_vel.SAC")+ read(path_dir_CESMD + "*Z.*.SAC")
    elif event_no == 1:
        event_title = 'beverlyhills'
        event_lat = 34.0541
        event_lon = -118.3929
        stream_cesmdN = read(path_dir_CESMD + "*N_vel.SAC") + read(path_dir_CESMD + "*N.*.SAC")
        stream_cesmdE = read(path_dir_CESMD + "*E_vel.SAC")+ read(path_dir_CESMD + "*E.*.SAC")
        stream_cesmdZ = read(path_dir_CESMD + "*Z_vel.SAC")+ read(path_dir_CESMD + "*Z.*.SAC")
    else: 
        print('unknown event file')
        
    # stream_cesmdN = read(path_dir_CESMD + "*BHN_vel.SAC") + read(path_dir_CESMD + "*BHN.*.SAC")
    # stream_cesmdE = read(path_dir_CESMD + "*BHE_vel.SAC") + read(path_dir_CESMD + "*BHE.*.SAC")

    # %% LON FIX
    
    stream_cesmd = stream_cesmdN + stream_cesmdE + stream_cesmdZ
    for tr in stream_cesmd:
        if tr.stats.sac.stlo > 0:
           tr.stats.sac.stlo = -tr.stats.sac.stlo 
    # %% STATIONS
    # stationFile = "/Users/bcbirkel/Documeevemt_latnts/GitHub/LABasin/all_stationmaster.txt"
    
    # Load station coords into arrays, many more stations than used
    st_netw  = []
    st_name  = []
    st_dist  = []
    st_az    = []
    st_baz   = []
    st_lat   = []
    st_lon   = []
    
    for tr in stream_cesmdN:
        st_netw.append(tr.stats.network)
        st_name.append(tr.stats.station)
        st_lat.append(tr.stats.sac.stla)
        st_lon.append(tr.stats.sac.stlo)
        distance = gps2dist_azimuth(event_lat, event_lon, tr.stats.sac.stla, tr.stats.sac.stlo) # Get traveltime and azimuth
        print(distance[0]/1000.)
        st_dist.append(distance[0]/1000.) # distance
        st_az.append(distance[1]) # azimuth
        st_baz.append(distance[2]) # back-azimuth
     
        
    # %% Initial plot   
    
    for tr in stream_cesmdN:
        distance = gps2dist_azimuth(event_lat, event_lon, tr.stats.sac.stla, tr.stats.sac.stlo) # Get traveltime and azimuth
        dist = distance[0]/1000
        tr.stats.distance = dist
    stream_cesmdN.plot(type='section')
    
    data_plot = stream_cesmd
    
    
    # figures for distance plots
    figN = plt.figure(0, figsize=[8,5])
    aN = figN.add_subplot(1, 1, 1)
    figE = plt.figure(1, figsize=[8,5])
    aE = figE.add_subplot(1, 1, 1)
    figZ = plt.figure(4, figsize=[8,5])
    aZ = figZ.add_subplot(1, 1, 1)
    
    
    # set up vars to loop through
    figs = [figN,figE,figZ]
    axes = [aN,aE,aZ]
    channels = ["BHN","BHE","BHZ"]
    
    # loop through each component
    for i in range(len(axes)):
        fig = figs[i]
        a = axes[i]
        cha = channels[i]
        
        a.set_ylabel("Distance from source (km)")    
        a.set_xlabel("Time (s)")
        a.set_title("Data for " + event +  " - " + cha)
        
        for tr in data_plot:
            if tr.stats.channel == cha:
                
                # set up vars
                distance = gps2dist_azimuth(event_lat, event_lon, tr.stats.sac.stla, tr.stats.sac.stlo) # Get traveltime and azimuth
                
                dist = distance[0]/1000

                # plot data
                if tr.stats.network == "CI":
                    a.plot(tr.times(reftime=start), tr.data+dist,c="k",linewidth=0.5)
                elif tr.stats.network == "CE":
                    a.plot(tr.times(reftime=start), tr.data+dist,c="k",linewidth=0.5)
                else:
                    a.plot(tr.times(reftime=start), tr.data+dist,c="k",linewidth=0.5)
                    
                a.set_ylim(0,40)
                a.set_xlim(0,50)
                
                # # add station names
                # if dist < ymax: 
                #     a.text(xmax-10,dist,tr.stats.sac.kstnm)
                    
    plt.show()
            
    # %% COMBINE STREAMS

        
    dataPath = './CompiledEvents/' + event + '/allData/fixed/'   
    if os.path.exists(dataPath):
        shutil.rmtree(dataPath)
    os.mkdir(dataPath)
    os.chdir(dataPath)
    for i in range(len(st_name)):
        tnT = False
        teT = False
        tzT = False
        tn = Trace()
        te = Trace()
        tz = Trace()
        trad = Trace()
        ttrans = Trace()
        
        for tr in stream_cesmd:
            if st_name[i] == tr.stats.station:
                dist = st_dist[i]
                az = st_az[i]
                baz = st_baz[i]
                
                if tr.stats.channel == "BHN":
                    # tr.stats.dist = dist
                    # tr.stats.sac.dist = dist
                    # tr.stats.sac.az = az
                    # tr.stats.sac.baz = baz
                    
                    # tn.data = tr.data
                    # tn.stats = tr.stats
                    # trad.data = tr.data
                    # trad.stats = tr.stats
                    tn = tr
                    trad = tr
                    
                    tnT = True
                
                if tr.stats.channel == "BHE":
                    # tr.stats.dist = dist
                    # tr.stats.sac.dist = dist
                    # tr.stats.sac.az = az
                    # tr.stats.sac.baz = baz
                    
                    # te.data = tr.data
                    # te.stats = tr.stats
                    # ttrans.data = tr.data
                    # ttrans.stats = tr.stats
                    te = tr
                    ttrans = tr

                    teT = True 
                    
                if tr.stats.channel == "BHZ":
                    tr.stats.dist = dist
                    tr.stats.sac.dist = dist
                    tr.stats.sac.az = az
                    tr.stats.sac.baz = baz
                    
                    tz.data = tr.data
                    tz.stats = tr.stats
                    
                    tz = tr
                    
                    tzT = True
                        
                if tnT == True and teT == True and tzT == True:
                    if not len(tn) == len(te):
                        start = max(tn.stats.starttime,te.stats.starttime)
                        end = min(tn.stats.endtime,te.stats.endtime)
                        sr = min(tn.stats.sampling_rate, te.stats.sampling_rate)
                        tn.resample(sr)
                        te.resample(sr)
                        tn = tn.slice(start,end,nearest_sample = False)
                        te = te.slice(start,end,nearest_sample = False)
                        print("warning: first cut")
                        if not len(tn) == len(te):
                            m = min(len(te), len(tn))
                            te.data = te.data[0:m]
                            tn.data = tn.data[0:m]
                            print("warning: cut streams - check them")
                    
                    trad.data, ttrans.data = rotate_ne_rt(tn.data,te.data,baz)

                    tn.stats.channel = "BHN"
                    tn.write(tr.stats.network + "_" + tr.stats.station + "_" + tn.stats.channel + "_vel.SAC", format="SAC")
                    
                    te.stats.channel = "BHE"
                    te.write(tr.stats.network + "_" + tr.stats.station + "_" + te.stats.channel + "_vel.SAC", format="SAC")
                    
                    tz.stats.channel = "BHZ"
                    tz.write(tr.stats.network + "_" + tr.stats.station + "_" + tz.stats.channel + "_vel.SAC", format="SAC")
                    
                    trad.stats.channel = "BHR"
                    trad.stats.sac.kcmpnm = "BHR"
                    trad.write(tr.stats.network + "_" + tr.stats.station + "_" + trad.stats.channel + "_vel.SAC", format="SAC")
                    
                    ttrans.stats.channel = "BHT"
                    ttrans.stats.sac.kcmpnm = "BHT"
                    ttrans.write(tr.stats.network + "_" + tr.stats.station + "_" + ttrans.stats.channel + "_vel.SAC", format="SAC")  # print("rotated synS!")  
                        
                    print("rotated cesmd!")
    


        # for tr in stream_synS:
        #     for trD in stream_cesmd:
        #         if tr.stats.station == trD.stats.station:
        #             tr.stats.starttime = trD.stats.starttime 
  
    # # %% FIX ROGUE STATIONS
    
    # stream_data = read(dataPath + "*_vel.SAC")

    # for tr in stream_data:
    #     print(tr.stats.network + ", " + tr.stats.station + ", " + tr.stats.channel + ", " + str(tr.max()))
    #     if abs(tr.max()) > 10000 and not tr.stats.network == "CE":
    #         signal.scale(tr, 100/tr.stats.sac.scale)
    #         print(tr.stats.station + ", " + tr.stats.channel + ", " + str(tr.max()) + ", " + str(tr.stats.sac.scale))
    
    #     tr.write(dataPath + tr.stats.network + "_" + tr.stats.station + "_" + tr.stats.channel + "_vel.SAC", format="SAC")
    
            
    # %% SET UP FIGURES FOR PLOTTING
    
    # stream_data = read(dataPath + "*_vel.SAC")
    # starts = []
    
    # for tr in stream_data:
    #     starts.append(tr.stats.starttime)
        
    # start = max(starts)
    # if event_no == 4:
    #     start = UTCDateTime("2009-05-18T03:39:37.000000Z")
    
    # stream_data = read(dataPath + "*_vel.SAC" ,starttime=start)
    # for tr in stream_data:
    #     for i in range(len(st_name)):
    #         if st_name[i] == tr.stats.station:
    #             tr.stats.dist = st_dist[i]
    #             tr.stats.sac.dist = st_dist[i]
    #             tr.stats.starttime = start
    
    #     tr.write(dataPath + tr.stats.network + "_" + tr.stats.station + "_" + tr.stats.channel + "_vel.SAC", format="SAC")
 
    # %% PLOTTING
    
    stream_data = read("./*_vel.SAC")
    
    # figures for distance plots
    figN = plt.figure(0, figsize=[8,5])
    aN = figN.add_subplot(1, 1, 1)
    figE = plt.figure(1, figsize=[8,5])
    aE = figE.add_subplot(1, 1, 1)
    figR = plt.figure(2, figsize=[8,5])
    aR = figR.add_subplot(1, 1, 1)
    figT = plt.figure(3, figsize=[8,5])
    aT = figT.add_subplot(1, 1, 1)
    figZ = plt.figure(4, figsize=[8,5])
    aZ = figZ.add_subplot(1, 1, 1)
                
    data_plot = stream_data
    
    # set up vars to loop through
    figs = [figN,figE,figR,figT,figZ]
    axes = [aN,aE,aR,aT,aZ]
    channels = ["BHN","BHE","BHR","BHT","BHZ"]
    
    # loop through each component
    for i in range(len(axes)):
        fig = figs[i]
        a = axes[i]
        cha = channels[i]
        
        a.set_ylabel("Distance from source (km)")    
        a.set_xlabel("Time (s)")
        a.set_title("Data for " + event +  " - " + cha)
        
        for tr in data_plot:
            if tr.stats.channel == cha:
                
                # set up vars
                distance = gps2dist_azimuth(event_lat, event_lon, tr.stats.sac.stla, tr.stats.sac.stlo) # Get traveltime and azimuth
                
                dist = distance[0]/1000

                # plot data
                if tr.stats.network == "CI":
                    a.plot(tr.times(reftime=start), tr.data+dist,c="r",linewidth=0.5)
                elif tr.stats.network == "CE":
                    a.plot(tr.times(reftime=start), tr.data+dist,c="k",linewidth=0.5)
                else:
                    a.plot(tr.times(reftime=start), tr.data+dist,c="k",linewidth=0.5)
                    
                a.set_ylim(0,40)
                a.set_xlim(0,50)
                
                # # add station names
                # if dist < ymax: 
                #     a.text(xmax-10,dist,tr.stats.sac.kstnm)
                    
    plt.show()

