function [m,s]=probase(res,bas,limres)
% CALCULA LA MEDIA Y LA DESVIACION ESTANDAR DE RECONOCIMIENTO
% PARA LA FUNCION DE PROBABILIDAD DIFUSA.
% LAS SERIES DE ENTRADA SON DOS, LA SERIE DE SALIDA res Y
% LAS SERIES DE ENTRENAMIENTO DIFUSO, (bas), LAS
% FUNCIONES DE ENTRENAMIENTO DEBEN TENER EL MISMO VECTOR "X" QUE
% "Y" Y DEBEN ESTAR EN COLUMNAS; F1(X) F2(X) F3(X) ...
%        UNIVERSIDAD NACIONAL AUTÓNOMA DE MÉXICO
%   INSTITUTO DE GEOFÍSICA - FACULTAD DE INGENIERÍA
%                INGENIERÍA GEOFÍSICA
% %     BÚSQUEDA DE MEDIA Y DESVIACIÓN ESTANDAR DE LA
% %     OCURRENCIA DE EVENTOS DE NATURALEZA ESTOCÁSTICA
% %     PARA UNA BASE DE ENTRENAMIENTO CON LÓGICA DIFUSA
%  ESCRITO POR: ALAN JUÁREZ ZÚÑIGA
% % % % % % % % % % % % % % % % % % % % % % % % % % % % % %

index=find(res>limres);
base=bas(index);
m=mean(base);
s=std(base);




